### ISSUE TITLE
[relay] make multiple tfchain rpc endpoints configurable

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_deployment#104]
example:

```
  grid_relay:
    depends_on:
      redis-rmb:
        condition: service_started
    container_name: grid_relay
    image: ghcr.io/threefoldtech/rmb-relay:${RMB_IMG}
    restart: unless-stopped
    networks:
      tfgrid_bknd:
    environment:
      - RMB_DOMAIN=relay.${DOMAIN}
      - SUBSTRATE_URL=ws://tfchain-public-node:9944
      - USER_PER_WORKER=1000
      - WORKERS=500
    command:
      - "--domain"
      - "relay.${DOMAIN}"
      - "-r"
      - "redis://redis-rmb:6379"
      - "-s"
      - "ws://tfchain-public-node:9944"
      - "-s"
      - "wss://tfchain.02.dev.grid.tf"
      - "-u"
      - "1000"
      - "-w"
      - "500"
      - "-l"
      - "0.0.0.0:80"
      - "--debug"
```
