### ISSUE TITLE
Proxy is not working after deploying

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_deployment#74]
After deploying the stack successfully and being able to use some of the environment, like graphql, I found some of them are not working(Proxy, TFchain and RMB).

```
    environment:
      ACTIVATION_SERVICE_URL: https://activation.harbydomain.gridtesting.xyz/activation/activate
      BRIDGE_TFT_ADDRESS: GBNOTAYUMXVO5QDYWYO2SOCOYIJ3XFIP65GKOQN7H65ZZSO6BK4SLWSC
      GRAPHQL_URL: https://graphql.harbydomain.gridtesting.xyz/graphql
      GRIDPROXY_URL: https://gridproxy.harbydomain.gridtesting.xyz
      MANUAL_URL: https://manual.grid.tf/
      MODE: main
      PLAYGROUND_URL: https://play.harbydomain.gridtesting.xyz
      RELAY_DOMAIN: wss://relay.harbydomain.gridtesting.xyz
      STATS_URL: https://stats.harbydomain.gridtesting.xyz
      STELLAR_NETWORK: main
      SUBSTRATE_URL: wss://tfchain.harbydomain.gridtesting.xyz
      VERSION: 2.5.2
```
